# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ndarray_pb2 as ndarray__pb2


class GrpcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ndarray = channel.unary_unary(
                '/numproto.protobuf.GrpcService/ndarray',
                request_serializer=ndarray__pb2.Input.SerializeToString,
                response_deserializer=ndarray__pb2.Coordinate.FromString,
                )


class GrpcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ndarray(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ndarray': grpc.unary_unary_rpc_method_handler(
                    servicer.ndarray,
                    request_deserializer=ndarray__pb2.Input.FromString,
                    response_serializer=ndarray__pb2.Coordinate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'numproto.protobuf.GrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GrpcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ndarray(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/numproto.protobuf.GrpcService/ndarray',
            ndarray__pb2.Input.SerializeToString,
            ndarray__pb2.Coordinate.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
