# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ndarray.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rndarray.proto\x12\x11numproto.protobuf\"7\n\x05Input\x12\x0f\n\x07ndarray\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\"\x1a\n\x07NDArray\x12\x0f\n\x07ndarray\x18\x01 \x01(\x0c\" \n\nCoordinate\x12\x12\n\ncoordinate\x18\x01 \x01(\x05\x32S\n\x0bGrpcService\x12\x44\n\x07ndarray\x12\x18.numproto.protobuf.Input\x1a\x1d.numproto.protobuf.Coordinate\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ndarray_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INPUT._serialized_start=36
  _INPUT._serialized_end=91
  _NDARRAY._serialized_start=93
  _NDARRAY._serialized_end=119
  _COORDINATE._serialized_start=121
  _COORDINATE._serialized_end=153
  _GRPCSERVICE._serialized_start=155
  _GRPCSERVICE._serialized_end=238
# @@protoc_insertion_point(module_scope)
